// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_end.Repositories;

#nullable disable

namespace back_end.Migrations
{
    [DbContext(typeof(WorkoutAppContext))]
    [Migration("20220923014444_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("back_end.Domain.Workout", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Title = "Workout 1"
                        });
                });

            modelBuilder.Entity("back_end.Domain.Workout", b =>
                {
                    b.OwnsMany("back_end.Domain.WorkoutStep", "Steps", b1 =>
                        {
                            b1.Property<int>("WorkoutID")
                                .HasColumnType("int");

                            b1.Property<int>("ID")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("ID"), 1L, 1);

                            b1.Property<string>("Instruction")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("Time")
                                .HasColumnType("datetime2");

                            b1.HasKey("WorkoutID", "ID");

                            b1.ToTable("WorkoutSteps");

                            b1.WithOwner("Workout")
                                .HasForeignKey("WorkoutID");

                            b1.Navigation("Workout");

                            b1.HasData(
                                new
                                {
                                    WorkoutID = 1,
                                    ID = 1,
                                    Instruction = "HELLO",
                                    Time = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                });
                        });

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
